### ISSUE TITLE
Şirket ile ilgili konuları farklı bir başlıkta birleştirmek üzerine

### ISSUE THREAD

**Issue by ilhan-mstf** [ifndefgt/yazilim-mulakatinda-isverene-sorular#1]
Öncelikle elinize sağlık, repo'ya ben de katkı sağlamak isterim ama öncesinde konuşup tartışmak istedim.
Benim aklımda;
- Şirketin bulunduğu pazar
- Şirketin müşterileri (kurumsal, son kullanıcı, yurt içi veya dışı ağırlıklı vs.)
- Şirketin kısa ve uzun vadeli hedefleri
- Şirketin büyüme ivmesi
- Şirkette çalışanların ortalama çalışma süresi

gibi sorular var. Bunlar için ayrı bir başlık açılabilir gibi geldi. Ne dersiniz?

**Comment by ilhan-mstf** [comment]
Şimdi fark ettim, medium yazınızda yukardaki başlıkların bazılarına değinmişsiniz. Direk repo'daki listeye bakınca 'Şirket' başlığı çok açıklayıcı gelmemişti. Belki de onun altına alt başlıklar eklenebilir.

**Comment by ifndefgt** [comment]
Listeyi kısa ve öz tutmak adına repodaki başlıkları çok detaylandırmadım. Açıkçası bu konuda yazının referans alınmasını bekiyorum.

> * Şirkette çalışanların ortalama çalışma süresi

Yazıdaki başlıkta bunu atlamışım, ilk fırsatta ekleyeceğim. Katkınız için teşekkürler.
